[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[etherscan]
3605 = { key = "empty_key", url = "${SOCKET_VERIFY_URL}" }
421614 = { key = "empty_key", url = "https://api-sepolia.arbiscan.io/api?" }
11155420 = { key = "empty_key", url = "https://optimism-sepolia.blockscout.com/api?" }
